### ISSUE TITLE
Cannot install in esphome

### ISSUE THREAD

**Issue by Allras82** [dmitry-cherkas/esphome-danfoss-eco#12]
missing "xxtea-lib.h" which is included in danfoss_eco/xxtea.h

src/esphome/components/danfoss_eco/xxtea.h:3:10: fatal error: xxtea-lib.h: No such file or directory

**Comment by djskrath** [comment]
I am also looking for help. I found something like this
![4282D410-F1E1-479F-B79E-0561D2FB2DED](https://user-images.githubusercontent.com/118557756/210279843-0f93b179-3e5a-40d8-a2ae-8926d9e38e71.png)

**Comment by dmitry-cherkas** [comment]
Hi @Allras82, could you please post your yaml config?
Seems like you are missing the `esphome -> libraries` dependency declaration, like:
```
esphome:
// ...
  libraries:
    - xxtea-iot-crypt@2.0.1
```

See some examples in the repo:
* https://github.com/dmitry-cherkas/esphome-danfoss-eco/blob/master/example_1_simple.yaml
* https://github.com/dmitry-cherkas/esphome-danfoss-eco/blob/master/example_2_home_assistant.yaml
* https://github.com/dmitry-cherkas/esphome-danfoss-eco/blob/master/example_3_multiple_climates.yaml

**Comment by dmitry-cherkas** [comment]
Hm.. looks like `xxtea-iot-crypt` is no longer available. I'll see what can be done about it.

**Comment by dmitry-cherkas** [comment]
Ok, seems I was wrong. I've prepared a new release, `v1.1.3` and for me it's building fine on HA `2023.1.7` and ESPHome `2022.12.5`. Please give it a try and let me know if you are facing any issues.

**Comment by RealLord** [comment]
Adding this lines to the esphome config help me to compiling this.
`libraries:
    - xxtea-iot-crypt@2.0.1`
And after that all is working fine!
