### ISSUE TITLE
Trying to compile/install issues an error

### ISSUE THREAD

**Issue by bipsendk** [dmitry-cherkas/esphome-danfoss-eco#2]
Trying to compile issues this error:

Compiling /data/thermostat-sleepingroom/.pioenvs/thermostat-sleepingroom/src/esphome/components/danfoss_eco/device.cpp.o
In file included from src/esphome/components/danfoss_eco/helpers.h:3:0,
                 from src/esphome/components/danfoss_eco/device.h:8,
                 from src/esphome/components/danfoss_eco/device.cpp:1:
src/esphome/components/danfoss_eco/xxtea.h:3:23: fatal error: xxtea-lib.h: No such file or directory

*******************************************************************
* Looking for xxtea-lib.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:xxtea-lib.h"
* Web  > https://platformio.org/lib/search?query=header:xxtea-lib.h
*
*******************************************************************

**Comment by drzero42** [comment]
@bipsendk I'm also seeing this error. Did you find a way to fix it?

**Comment by drzero42** [comment]
Okay, nevermind, I found the solution.
For future seekers: Add the needed libraries like this:
```
esphome:
  libraries:
    - xxtea-iot-crypt@2.0.1
```
